### ISSUE TITLE
[1.1.0] Required Key Numbers Do Not Seem To Be Working

### ISSUE THREAD

**Issue by jsnbrown1989** [SimonFlash/TeslaCrate#2]
[Current Nucleus Info](https://cdn.discordapp.com/attachments/319162038150627329/326422386067111938/nucleus-info-20170619-200432.txt)

Required key numbers do not seem to be working atm. I have 7 crate keys and its still saying it requires 5 to open.

This is while using Physical keys. Virtual Keys do work (Worth noting that these are cleared during a reload/restart, I'm betting this is to be expected.)

If the crate is only looking for one key, it works as expected.

![multiplekey issue](https://user-images.githubusercontent.com/4334101/27312950-53f7c98c-5539-11e7-99f6-574152798e8f.PNG)

**Comment by SimonFlash** [comment]
I'll be honest, I really don't understand this one but I fixed it. On a secondary note, the keys not loading (they're saved properly, just not loaded after a restart) seems to be due to the implementation of the users UUID in Sponge. This has been fixed, but I'm going to be researching this more.
