### ISSUE TITLE
[1.1.1] physical Keys do not need lore to open chest

### ISSUE THREAD

**Issue by jsnbrown1989** [SimonFlash/TeslaCrate#4]
I am able to pull a tripwire hook out of creative and open any chest. 

If it has lore then yes, it only opens the chest the lore is associated with.

**Comment by SimonFlash** [comment]
I kindof forgot about this one for a while. This is caused by the Sponge DataAPI not being available during main initialization. I've made the needed changed and I'll release the fix momentarily.
