### ISSUE TITLE
Add gradle wrapper to support Jitpack.io compatibility.

### ISSUE THREAD

**Issue by Kitsune30** [SimonFlash/TeslaCrate#8]
Currently Jitpack is throwing back an error and I think it can be solved by adding the wrapper to the repo.

https://jitpack.io/com/github/SimonFlash/TeslaCrate/v2.2.1/build.log

Adding this would make TeslaCrates on par with TeslaLibs with dependency handling.

**Comment by SimonFlash** [comment]
As development is now focused on v3 which should address this issue, it can be closed. It seems like the pr1 and pr2 releases work fine, and I've 'fixed' pr3 being on the wrong branch but can't verify that JitPack is working with it properly. If this persists when pr4 is released, we can reopen the issue.
